[book]
authors = ["FrilLab"]
language = "en"
src = "src"
title = "FrilVault Architecture"

[build]
build-dir = "book"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/FrilLab/frilvault"
site-url = "/frilvault/"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
